Pushed new changes

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -97,9 +97,12 @@ jobs:
           echo "Deploying to production..."
           echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
           ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} "
-          ls &&
-          cd Flask-Deployment/ &&
-          ls &&
+          mkdir -p Flask-Deployment &&
+          if [ ! -d Flask-Deployment ]; then
+            echo 'Directory Flask-Deployment does not exist and could not be created.'
+            exit 1
+          fi
+          cd Flask-Deployment &&
           git pull &&
           sudo systemctl stop flask-app &&
           sudo systemctl daemon-reload &&
